"""create standard table

Revision ID: 1a6287783460
Revises:
Create Date: 2019-03-10 18:16:37.106333

"""
from alembic import op
import sqlalchemy as sa

import backend

# revision identifiers, used by Alembic.
revision = '1a6287783460'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard',
    sa.Column('full_code', sa.String(length=140), nullable=False, primary_key=True),
    sa.Column('standard', sa.String(length=140), nullable=False),
    sa.Column('tag', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(length=None), nullable=False)
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard')
    # ### end Alembic commands ###
