"""
create blog models

Revision ID: 65c9668d1396
Revises:
Create Date: 2017-10-11 17:47:12.712133
"""

from alembic import op
import sqlalchemy as sa


import backend

# revision identifiers, used by Alembic.
revision = '65c9668d1396'
down_revision = None
branch_labels = ('blog',)
depends_on = '8036f244db77'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('publish_date', backend.database.types.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', backend.database.types.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('header_image', sa.String(length=255), nullable=True),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('article_series_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['article_series_id'], ['series_article.id'], name=op.f('fk_article_article_series_id_series_article')),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_article_author_id_user')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_article_category_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')

    # ### end Alembic commands ###
